FROM node:20-alpine

WORKDIR /apps
COPY package.json .
COPY tsconfig.json .

RUN npm install

COPY . .
RUN npm run build

ARG PORT=12318
ARG HOST=${HOST}
ARG ACCEPTED_CLIENTS=${ACCEPTED_CLIENTS}
ARG DATABASE_CONN_STRING=${DATABASE_CONN_STRING}
ARG DATABASE_NAME=${DATABASE_NAME}
ARG ACCESS_TOKEN_EXP=${ACCESS_TOKEN_EXP}
ARG REF_TOKEN_EXP=${REF_TOKEN_EXP}
ARG ACCESS_TOKEN_SEC=${ACCESS_TOKEN_SEC}
ARG REFRESH_TOKEN_SEC=${REFRESH_TOKEN_SEC}
ARG X_API_EXP=${X_API_EXP}
ARG X_API_SEC=${X_API_SEC}
ARG PASSPHRASE=${PASSPHRASE}
ARG SALT=${SALT}
ARG CV_URL=${CV_URL}
ARG PHOTO_URL=${PHOTO_URL}

ENV PORT=12318
ENV HOST=${HOST}
ENV ACCEPTED_CLIENTS=${ACCEPTED_CLIENTS}
ENV DATABASE_CONN_STRING=${DATABASE_CONN_STRING}
ENV DATABASE_NAME=${DATABASE_NAME}
ENV ACCESS_TOKEN_EXP=${ACCESS_TOKEN_EXP}
ENV REF_TOKEN_EXP=${REF_TOKEN_EXP}
ENV ACCESS_TOKEN_SEC=${ACCESS_TOKEN_SEC}
ENV X_API_EXP=${X_API_EXP}
ENV X_API_SEC=${X_API_SEC}
ENV PASSPHRASE=${PASSPHRASE} 
ENV SALT=${SALT}
ENV CV_URL=${CV_URL}
ENV PHOTO_URL=${PHOTO_URL}

RUN rm -rf src
RUN rm -rf Dockerfile .dockerignore .prettierrc .prettierignore .gitignore tsconfig.json

EXPOSE 12318
CMD [ "npm","start" ]