sonar.projectKey=portfolio-builder-backend
sonar.projectName=Portfolio Builder Backend
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.exclusions=node_modules/**,dist/**,logs/**,scripts/**,deploy.ps1,**/*.spec.ts,**/*.test.ts,.vscode/**