import { Request, Response } from 'express';
import { ApiResponse, HTTP_STATUS_CODES, Status } from '../api';
import { Events } from '../models/events.model';
import { EventNames } from '../constant';
import { HandleException } from '../decorators/exception.decorator';
import { CustomReq, ICaptchaValidate } from '../interfaces';
import { decrypt, encrypt, performParallelTask } from '../helpers';
import { WebsiteUpdates } from '../models/website_updates';
import Queries from '../db/queries';
import connectRedis from '@config/redis.config';
import { PageStatus } from '@models/page_status.model';
import * as crypto from "node:crypto";
import { init } from '@config/logs.config';

class HomeController {
  @HandleException()
  public static ping(request: Request, response: Response): Response {
    const reply = new ApiResponse(
      Status.SUCCESS,
      'Pong',
      { version: 'v1' },
      request.ip || 'localhost'
    );

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }

  @HandleException()
  public static async shutdown(request: CustomReq, response: Response): Promise<void> {
    const { authenticatedUser } = request;
    const reply = new ApiResponse(Status.SUCCESS, 'Shutdown was successfull');

    await Events.create({ eventName: EventNames.SHUT_DOWN, firedBy: authenticatedUser._id });
    response.status(HTTP_STATUS_CODES.OK).json(reply);
    process.exit(0);
  }

  @HandleException()
  public static async captcha(request: Request, response: Response): Promise<Response> {
    const reply = new ApiResponse();
    const REDIS_CLIENT = connectRedis();
    const alphaNumericLetters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789$%@!(^)';
    let captchaLen = Number(process.env.CAPTCHA_LEN) || 6;
    let captcha = '';
    const keyName = "portfolio_backend:captcha";
    const logger = init();

    for (let index = 0; index < Number(captchaLen); index++) {
      captcha += alphaNumericLetters[crypto.randomInt(0, alphaNumericLetters.length)];
    }

    const token = await encrypt(captcha);
    await REDIS_CLIENT.setex(`${keyName}:${captcha}`, 300, token);

    logger.info({ message: `Captcha - ${captcha} has been generated at ${new Date().toISOString()} by ${request.ip || "0.0.0.0"}`, instant: Date.now() });

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Captcha generated';
    reply.DATA = { captcha };
    reply.ENTRY_BY = request.ip || '0.0.0.0';

    return response.status(HTTP_STATUS_CODES.CREATED).json(reply);
  }

  @HandleException()
  public static async captchaValidate(request: Request, response: Response): Promise<Response> {
    const reply = new ApiResponse();
    let { captcha } = request.query as unknown as ICaptchaValidate;
    const REDIS_CLIENT = connectRedis();
    const logger = init();
    const keyName = `portfolio_backend:captcha:${captcha}`;
    const token = await REDIS_CLIENT.get(keyName);

    if (!token) {
      reply.STATUS = Status.UNAUTHORISED;
      reply.MESSAGE = 'Invalid captcha';
      reply.ENTRY_BY = request.ip || '0.0.0.0';

      logger.info({ message: `The token of captcha ${captcha} is missing, please check the typos in captcha provided.`, instant: Date.now() });
      return response.status(HTTP_STATUS_CODES.UNAUTHORISED).json(reply);
    }

    const decryptedCaptcha = await decrypt(token);

    if (decryptedCaptcha !== captcha) {
      reply.STATUS = Status.UNAUTHORISED;
      reply.MESSAGE = 'Invalid captcha';
      reply.ENTRY_BY = request.ip || '0.0.0.0';

      logger.info({ message: `Provided captcha does not match with the one which has been generated by the system, please check the typos in captcha provided.`, instant: Date.now() });
      return response.status(HTTP_STATUS_CODES.UNAUTHORISED).json(reply);
    }

    await REDIS_CLIENT.del(keyName);
    logger.info({ message: `Captcha - ${captcha} has been successfully verified by the system.`, instant: Date.now() });

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Captcha verified';
    reply.ENTRY_BY = request.ip || '0.0.0.0';

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }

  @HandleException()
  public static async listPageStatus(request: Request, response: Response): Promise<Response> {
    const reply = new ApiResponse();
    const url = request.query.url;
    const query = url ? { url } : {};
    const pageStatusRecords = await PageStatus.find(query, { url: 1, status: 1 }, { lean: true });

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = "Page status fetched successfully";
    reply.DATA = pageStatusRecords;
    reply.ENTRY_BY = request.ip || "0.0.0.0";

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }

  @HandleException()
  public static notFound(request: Request, response: Response): Response {
    const reply = new ApiResponse();

    reply.STATUS = Status.NOT_FOUND;
    reply.MESSAGE = "This route does not exists";
    reply.ENTRY_BY = request.ip || "0.0.0.0";

    return response.status(HTTP_STATUS_CODES.NOT_FOUND).json(reply);
  }

  @HandleException()
  public static async updateWebsite(request: CustomReq, response: Response): Promise<Response> {
    const reply = new ApiResponse();
    const websiteOwner = request.authenticatedUser._id;

    const updatedWebsiteRecord = await WebsiteUpdates.findOneAndUpdate(
      { website_owner: websiteOwner },
      { $set: { updatedAt: new Date(Date.now()), portfolio_url: request.body.portfolio_url } },
      { runValidators: true, new: true, upsert: true }
    );

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Website updated successfully';
    reply.DATA = updatedWebsiteRecord;
    reply.ENTRY_BY = request.authenticatedUser.email || request.ip || '0.0.0.0';

    return response.status(HTTP_STATUS_CODES.UPDATED).json(reply);
  }

  @HandleException()
  public static async getLastModifiedDate(
    request: CustomReq,
    response: Response
  ): Promise<Response> {
    const reply = new ApiResponse();
    const { portfolio_url } = request.query;

    if (!portfolio_url) {
      reply.STATUS = Status.VALIDATION;
      reply.MESSAGE = 'All fields are required';
      reply.ENTRY_BY = request.ip || '0.0.0.0';

      return response.status(HTTP_STATUS_CODES.BAD_REQUEST).json(reply);
    }

    const websiteRecord = await WebsiteUpdates.findOne({ portfolio_url }).select('updatedAt');

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Website updated successfully';
    reply.DATA = { lastModifiedAt: websiteRecord?.updatedAt };
    reply.ENTRY_BY = request.ip || '0.0.0.0';

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }

  @HandleException()
  public static async updateWebsiteAccess(
    request: CustomReq,
    response: Response
  ): Promise<Response> {
    const reply = new ApiResponse();
    const REDIS_CLIENT = connectRedis();
    const cachedWebViewEventKey = 'portfolio-backend:events:website-view-event';
    const cachedWebViewEvents = JSON.parse(
      (await REDIS_CLIENT.get(cachedWebViewEventKey)) || JSON.stringify({})
    ) as Array<Record<string, any>>;
    const payload = [
      {
        eventName: EventNames.PORTFOLIO_WEBSITE_VIEWED,
        firedBy: request.ip || '0.0.0.0',
      },
    ];

    if (!cachedWebViewEvents || !cachedWebViewEvents?.length) {
      await REDIS_CLIENT.set(cachedWebViewEventKey, JSON.stringify(payload));
    } else {
      cachedWebViewEvents.push(payload[0]);
      await REDIS_CLIENT.set(cachedWebViewEventKey, JSON.stringify(cachedWebViewEvents));
    }

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Event created successfully';
    reply.ENTRY_BY = request.ip || '0.0.0.0';

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }

  @HandleException()
  public static async getWebsiteAccess(request: CustomReq, response: Response): Promise<Response> {
    const reply = new ApiResponse();
    const eventName = EventNames.PORTFOLIO_WEBSITE_TOTAL_VIEWS_FETCHED;
    let [views] = await performParallelTask([
      Events.aggregate(Queries.getTotalViews()),
      Events.create({ eventName, firedBy: request.ip }),
    ]);

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Events fetched successfully';
    reply.DATA = views[0] || {};
    reply.ENTRY_BY = request.ip || '';

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }

  @HandleException()
  public static async getMonthlyWebViews(
    request: CustomReq,
    response: Response
  ): Promise<Response> {
    const reply = new ApiResponse();
    const eventName = EventNames.PORTFOLIO_WEBSITE_MONTHLY_VIEWS_FETCHED;
    let [views] = await performParallelTask([
      Events.aggregate(Queries.getMonthlyWebsiteViews(new Date())),
      Events.create({ eventName, firedBy: request.ip }),
    ]);

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Events fetched successfully';
    reply.DATA = views[0] || { view_count: 0 };
    reply.ENTRY_BY = request.ip || '';

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }

  @HandleException()
  public static async getDailyWebsiteViews(
    request: CustomReq,
    response: Response
  ): Promise<Response> {
    const reply = new ApiResponse();
    const eventName = EventNames.PORTFOLIO_WEBSITE_VIEW_FETCHED;
    let [views] = await performParallelTask([
      Events.aggregate(Queries.getDailyWebsiteViews(new Date())),
      Events.create({ eventName, firedBy: request.ip }),
    ]);

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Events fetched successfully';
    reply.DATA = views[0] || { view_count: 0 };
    reply.ENTRY_BY = request.ip || '';

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }

  @HandleException()
  public static async getTodayViewsDetails(
    request: Request,
    response: Response
  ): Promise<Response> {
    const reply = new ApiResponse();

    const currentDate = new Date();
    const todayDate = `${currentDate.getFullYear()}-${currentDate.getMonth() + 1
      }-${currentDate.getDate()}`;
    const nextDate = `${currentDate.getFullYear()}-${currentDate.getMonth() + 1}-${currentDate.getDate() + 1
      }`;
    const viewDetails = await Events.find({
      $and: [
        { eventName: EventNames.PORTFOLIO_WEBSITE_VIEWED },
        {
          createdAt: {
            $lte: new Date(nextDate),
            $gte: new Date(todayDate),
          },
        },
      ],
    });

    reply.STATUS = Status.SUCCESS;
    reply.MESSAGE = 'Details fetched successfully';
    reply.DATA = viewDetails;
    reply.ENTRY_BY = request.ip || '0.0.0.0';

    return response.status(HTTP_STATUS_CODES.OK).json(reply);
  }
}

export default HomeController;
